import { Activity, Download, Pause, Play, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { EmptyState, Panel, SectionHeading } from "../components/Common";
import type { EkoEvent, LinkStats } from "../types";

export function LogsPage({ events, stats }: { events: EkoEvent[]; stats: LinkStats }) {
  const [paused, setPaused] = useState(false); const [snapshot, setSnapshot] = useState(events); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all");
  useEffect(() => { if (!paused) setSnapshot(events); }, [events, paused]);
  const categories = useMemo(() => Array.from(new Set(snapshot.map((event) => event.name.split(".")[0]))).sort(), [snapshot]);
  const filtered = snapshot.filter((event) => (category === "all" || event.name.startsWith(`${category}.`) || event.name === category) && `${event.name} ${JSON.stringify(event.payload)} ${event.correlation_id ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const exportEvents = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(filtered, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `eko-events-${new Date().toISOString().replace(/[:.]/g, "-")}.json`; link.click(); URL.revokeObjectURL(url); };
  return <Panel className="logs-panel"><SectionHeading kicker={`${stats.kind === "ble" ? "BLE" : "WEBSOCKET"} EVENT STREAM`} title={`${filtered.length} runtime events`} action={<div className="heading-actions"><button className="secondary-button" onClick={() => setPaused((value) => !value)}>{paused ? <Play size={16} /> : <Pause size={16} />}{paused ? "Resume" : "Pause"}</button><button className="secondary-button" onClick={exportEvents} disabled={!filtered.length}><Download size={16} />Export</button></div>} /><div className="log-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter name, payload, or correlation ID" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><span className={`stream-state ${paused ? "paused" : ""}`}><i />{paused ? "Paused" : stats.connected ? "Live" : "Offline"}</span></div><div className="log-table"><header><span>Time</span><span>Event</span><span>Payload</span><span>Correlation</span></header>{filtered.length ? filtered.map((event, index) => <article key={`${event.timestamp}-${event.name}-${index}`}><time>{new Date(event.timestamp).toLocaleTimeString()}</time><strong>{event.name}</strong><code>{JSON.stringify(event.payload)}</code><span>{event.correlation_id ?? "—"}</span></article>) : <EmptyState icon={Activity} title="No matching events" message="Events appear here as the EKO runtime publishes them." />}</div></Panel>;
}
