import { Database, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import type { EkoClient } from "../client";
import { EmptyState, Panel, SectionHeading } from "../components/Common";
import type { MemoryRecord } from "../types";

export function MemoryPage({ client }: { client: EkoClient | null }) {
  const [memories, setMemories] = useState<MemoryRecord[]>([]); const [query, setQuery] = useState(""); const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (search = "") => { if (!client) { setMemories([]); return; } try { setMemories((await client.memories(search)).memories); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load memories"); } }, [client]);
  useEffect(() => { void load(); }, [load]);
  const remember = async (event: FormEvent) => { event.preventDefault(); const content = draft.trim(); if (!client || !content || busy) return; setBusy(true); try { await client.remember(content); setDraft(""); setQuery(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save memory"); } finally { setBusy(false); } };
  const forget = async (id: number) => { if (!client) return; setBusy(true); try { await client.forget(id); await load(query); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not delete memory"); } finally { setBusy(false); } };
  return <div className="page-grid memory-page"><Panel className="memory-main"><SectionHeading kicker="LONG-TERM MEMORY" title={`${memories.length} saved records`} action={<button className="icon-button" onClick={() => void load(query)}><RefreshCw size={16} /></button>} /><form className="search-box" onSubmit={(event) => { event.preventDefault(); void load(query); }}><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search memory content and tags" /><button>Search</button></form>{error && <p className="inline-error">{error}</p>}<div className="memory-list">{memories.length ? memories.map((memory, index) => <article key={memory.id}><span className="memory-id">#{memory.display_index ?? index + 1}</span><div><strong>{memory.content}</strong><div className="memory-meta"><span>{memory.kind}</span><time>{new Date(memory.updated_at).toLocaleString()}</time>{memory.tags.map((tag) => <em key={tag}>{tag}</em>)}</div></div><button className="delete-button" disabled={busy} onClick={() => void forget(memory.id)}><Trash2 size={16} /></button></article>) : <EmptyState icon={Database} title="No matching memories" message={client ? "Save a memory or broaden your search." : "Connect to EKO to read its memory bank."} />}</div></Panel><Panel className="memory-create"><SectionHeading kicker="ADD RECORD" title="Teach EKO" action={<Plus size={19} />} /><p className="muted-copy">Store a durable fact in EKO's SQLite memory. Display numbers recalculate automatically after every change.</p><form onSubmit={remember}><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Remember that…" rows={7} disabled={!client || busy} /><button className="primary-button" disabled={!client || busy || !draft.trim()}>{busy ? <RefreshCw className="spin" size={17} /> : <Plus size={17} />}Save memory</button></form><div className="storage-note"><Database size={18} /><p>The record remains on the robot and can be recalled by text or voice.</p></div></Panel></div>;
}
