import { AudioLines, Bluetooth, Camera, Cpu, ExternalLink, Gauge, Link2, RotateCcw, ShieldCheck, Trash2, Wifi } from "lucide-react";
import { useState } from "react";
import type { EkoClient } from "../client";
import { Panel, SectionHeading, Toggle } from "../components/Common";
import type { ConnectionProfile, LinkStats, RuntimeSettings, StatusPayload } from "../types";

export function SettingsPage({ client, status, stats, profile, onSettings, onConnection, onForget }: { client: EkoClient | null; status: StatusPayload | null; stats: LinkStats; profile: ConnectionProfile; onSettings: (settings: RuntimeSettings) => void; onConnection: () => void; onForget: () => void }) {
  const [error, setError] = useState<string | null>(null); const settings = status?.settings;
  const update = async (changes: Partial<RuntimeSettings>) => { if (!client) return; try { onSettings(await client.updateSettings(changes)); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update setting"); } };
  return <div className="page-grid settings-page"><Panel className="runtime-settings"><SectionHeading kicker="RUNTIME BEHAVIOR" title="Operator preferences" action={<RotateCcw size={19} />} />{error && <p className="inline-error">{error}</p>}<Toggle checked={Boolean(settings?.voice_responses)} label="Voice responses" description="Speak replies through EKO" disabled={!client} onChange={(value) => void update({ voice_responses: value })} /><Toggle checked={Boolean(settings?.wakeword_enabled)} label="Wake-word listener" description="Allow event-driven microphone activation" disabled={!client || !settings?.audio_enabled} onChange={(value) => void update({ wakeword_enabled: value })} /><Toggle checked={Boolean(settings?.memory_auto_inject)} label="Memory context" description="Attach relevant saved memories" disabled={!client} onChange={(value) => void update({ memory_auto_inject: value })} /><Toggle checked={Boolean(settings?.web_search_enabled)} label="Web search service" description="Permit current-information requests" disabled={!client} onChange={(value) => void update({ web_search_enabled: value })} /><Toggle checked={Boolean(settings?.camera_on_demand)} label="Camera capture" description="Permit explicit snapshots" disabled={!client || !settings?.vision_enabled} onChange={(value) => void update({ camera_on_demand: value })} /></Panel>
    <Panel className="connection-settings"><SectionHeading kicker="ACTIVE LINK" title="Connection" action={stats.kind === "ble" ? <Bluetooth size={19} /> : <Wifi size={19} />} /><dl className="detail-list"><div><dt>Transport</dt><dd>{stats.kind === "ble" ? "Bluetooth LE" : stats.kind === "wifi" ? "Wi-Fi / HTTPS" : "Disconnected"}</dd></div><div><dt>Endpoint/device</dt><dd className="endpoint-value">{stats.connected ? stats.label : profile.kind === "wifi" ? profile.wifiUrl : profile.bleDeviceId || "Not paired"}</dd></div><div><dt>Latency</dt><dd>{stats.latencyMs == null ? "—" : `${stats.latencyMs} ms`}</dd></div><div><dt>Last update</dt><dd>{stats.lastUpdated?.toLocaleTimeString() ?? "—"}</dd></div><div><dt>Robot version</dt><dd>{status?.robot.version ?? "—"}</dd></div></dl><button className="connection-change" onClick={onConnection}><Link2 size={17} />Change connection</button><button className="forget-button" onClick={onForget}><Trash2 size={16} />Forget saved link and token</button><p className="config-hint"><ExternalLink size={16} />Wi-Fi from GitHub Pages requires HTTPS/WSS. BLE requires Web Bluetooth and the EKO bridge running on the Pi.</p></Panel>
    <Panel className="module-settings"><SectionHeading kicker="DEVICE MODULES" title="Restart-managed configuration" action={<Cpu size={19} />} /><div className="module-grid"><article><Gauge size={20} /><div><strong>Motion hardware</strong><span>{settings?.hardware_enabled ? "Enabled" : "Safety locked"}</span></div></article><article><Camera size={20} /><div><strong>Vision</strong><span>{settings?.vision_enabled ? "Enabled" : "Disabled"}</span></div></article><article><AudioLines size={20} /><div><strong>Audio</strong><span>{settings?.audio_enabled ? "Enabled" : "Disabled"}</span></div></article></div><div className="restart-note"><ShieldCheck size={19} /><p>GPIO enablement, motor pins, provider credentials, and device backends are intentionally changed on the Pi and applied with a controlled restart.</p></div></Panel>
  </div>;
}
