import { Aperture, Bluetooth, Camera, Clock3, ImageOff, RefreshCw, ShieldCheck, Wifi } from "lucide-react";
import { useState } from "react";
import type { EkoClient } from "../client";
import { EmptyState, Panel, SectionHeading, Toggle } from "../components/Common";
import type { LinkStats, RuntimeSettings, StatusPayload, VisionSnapshot } from "../types";

export function VisionPage({ client, status, stats, onSettings }: { client: EkoClient | null; status: StatusPayload | null; stats: LinkStats; onSettings: (settings: RuntimeSettings) => void }) {
  const [snapshot, setSnapshot] = useState<VisionSnapshot | null>(null); const [capturing, setCapturing] = useState(false); const [error, setError] = useState<string | null>(null);
  const settings = status?.settings; const ready = Boolean(client && (settings?.vision_enabled || (settings?.mock_mode && settings?.mock_connected)) && settings?.camera_on_demand);
  const capture = async () => { if (!client) return; setCapturing(true); setError(null); try { setSnapshot(await client.snapshot()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Camera capture failed"); } finally { setCapturing(false); } };
  const setPolicy = async (camera_on_demand: boolean) => { if (!client) return; try { onSettings(await client.updateSettings({ camera_on_demand })); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update camera policy"); } };
  return <div className="page-grid vision-page"><Panel className="camera-panel"><SectionHeading kicker="ON-DEMAND CAMERA" title="Latest frame" action={<button className="primary-button" onClick={() => void capture()} disabled={!ready || capturing}>{capturing ? <RefreshCw className="spin" size={17} /> : <Camera size={17} />}{capturing ? "Receiving…" : "Capture frame"}</button>} />{stats.kind === "ble" && <div className="transport-warning"><Bluetooth size={18} /><p>BLE snapshot transfer is supported through chunking but can be slow. Wi-Fi is recommended for camera images.</p></div>}<div className="camera-viewport">{snapshot ? <><img src={`data:${snapshot.mime_type};base64,${snapshot.image_base64}`} alt="Latest frame from EKO" /><div className="frame-overlay"><span>CAM 01</span><time><Clock3 size={13} />{new Date(snapshot.captured_at * 1000).toLocaleString()}</time></div></> : <EmptyState icon={ImageOff} title="No captured frame" message="EKO keeps its camera off until you explicitly request one frame." />}</div>{error && <p className="inline-error">{error}</p>}</Panel><div className="vision-sidebar"><Panel><SectionHeading kicker="PRIVACY POLICY" title="Camera access" action={<ShieldCheck size={19} />} /><Toggle checked={Boolean(settings?.camera_on_demand)} label="On-demand capture" description="Permit explicit one-frame requests" disabled={!client || (!settings?.vision_enabled && !settings?.mock_mode)} onChange={(value) => void setPolicy(value)} /><div className="privacy-note"><Camera size={18} /><p>The Pi requests a JPEG only when needed and deletes its temporary file after processing. Browser preview remains local.</p></div></Panel><Panel><SectionHeading kicker="PERCEPTION" title="Vision status" action={<Aperture size={19} />} /><dl className="detail-list"><div><dt>Runtime module</dt><dd className={ready ? "ready" : "disabled"}>{settings?.mock_mode ? "Browser adapter" : settings?.vision_enabled ? "Pi camera" : "Disabled"}</dd></div><div><dt>Policy</dt><dd>{settings?.camera_on_demand ? "On request" : "Blocked"}</dd></div><div><dt>Link</dt><dd>{stats.kind === "ble" ? "BLE chunks" : "HTTPS JPEG"}</dd></div><div><dt>Recommended</dt><dd>{stats.kind === "ble" ? <span><Wifi size={12} /> Wi-Fi</span> : "Current link"}</dd></div></dl></Panel></div></div>;
}
