import { Bluetooth, Check, LockKeyhole, Radio, RefreshCw, ShieldCheck, Wifi, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { ConnectionProfile, LinkStats, TransportKind } from "../types";

export function ConnectionDialog({ open, profile, stats, bleSupported, canClose, onClose, onConnect }: { open: boolean; profile: ConnectionProfile; stats: LinkStats; bleSupported: boolean; canClose: boolean; onClose: () => void; onConnect: (profile: ConnectionProfile) => Promise<void> }) {
  const [draft, setDraft] = useState(profile);
  useEffect(() => setDraft(profile), [profile]);
  if (!open) return null;
  const choose = (kind: TransportKind) => setDraft((value) => ({ ...value, kind }));
  return <div className="modal-backdrop" role="presentation"><section className="connection-dialog" role="dialog" aria-modal="true" aria-labelledby="connect-title"><header><div><span className="eyebrow">EKO LINK</span><h2 id="connect-title">Connect to your robot</h2></div>{canClose && <button className="icon-button" onClick={onClose} aria-label="Close"><X size={17} /></button>}</header><div className="transport-tabs"><button className={draft.kind === "wifi" ? "selected" : ""} onClick={() => choose("wifi")}><Wifi size={20} /><strong>Wi-Fi</strong><span>Full control · HTTPS/WSS</span></button><button className={draft.kind === "ble" ? "selected" : ""} onClick={() => choose("ble")} disabled={!bleSupported}><Bluetooth size={20} /><strong>Bluetooth LE</strong><span>{bleSupported ? "Nearby direct link" : "Not supported here"}</span></button></div>{draft.kind === "wifi" ? <div className="connection-fields"><label>Robot API address<input value={draft.wifiUrl} onChange={(event) => setDraft((value) => ({ ...value, wifiUrl: event.target.value }))} placeholder="https://eko.example.com" inputMode="url" /><small>GitHub Pages requires a trusted HTTPS endpoint.</small></label><label>API access token<div className="input-with-icon"><LockKeyhole size={16} /><input type="password" value={draft.wifiToken} onChange={(event) => setDraft((value) => ({ ...value, wifiToken: event.target.value }))} placeholder="Required for remote access" autoComplete="current-password" /></div></label></div> : <div className="ble-setup"><Bluetooth size={31} /><h3>Pair with EKO</h3><p>Start the EKO BLE bridge on the Raspberry Pi, then choose the device named <strong>EKO</strong>. The browser must show its device picker from this button.</p><label>BLE bridge token <input type="password" value={draft.bleToken} onChange={(event) => setDraft((value) => ({ ...value, bleToken: event.target.value }))} placeholder="Optional physical-link token" /></label>{draft.bleDeviceId && <span className="remembered-device"><Check size={14} />Previously paired device available</span>}</div>}<label className="remember-choice"><input type="checkbox" checked={draft.autoReconnect} onChange={(event) => setDraft((value) => ({ ...value, autoReconnect: event.target.checked }))} />Reconnect automatically and remember credentials on this browser</label>{stats.error && <p className="dialog-error">{stats.error}</p>}<button className="dialog-connect" disabled={stats.connecting || (draft.kind === "wifi" && !draft.wifiUrl.trim())} onClick={() => void onConnect(draft).catch(() => undefined)}>{stats.connecting ? <RefreshCw className="spin" size={18} /> : draft.kind === "wifi" ? <Radio size={18} /> : <Bluetooth size={18} />}{stats.connecting ? "Connecting…" : `Connect over ${draft.kind === "wifi" ? "Wi-Fi" : "Bluetooth"}`}</button><footer><ShieldCheck size={16} /><span>The robot remains authoritative for GPIO safety, speed limits, and dead-man stop behavior.</span></footer></section></div>;
}
